import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/navigation/footer";
import { Navigation } from "@/components/navigation/navigation";
import { AuthProvider } from "@/context/AuthContext";
import { Breadcrumb } from "@/ui/components/breadcrumb/breadcrumb";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets : ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "My First Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${inter.className} antialiased`}>
      <AuthProvider>
          <Toaster position="top-center" />
          {children}
      </AuthProvider>
      </body>
    </html>
  );
}
